### ISSUE TITLE
Something broke...

### ISSUE THREAD

**Issue by jangrewe** [JoelBesada/pasteboard#33]
I'm sorry if i can't be more precise, but it looks like one of the recent commits broke our pasteboard. When trying to access and image, we always get:

```

Express
500 ReferenceError: /srv/www/pasteboard/views/image.ejs:47 45| <div class="url"> 46| <span>URL:</span> >> 47| <input type="text" value="<%= longURL %>" readonly onClick="this.select();"> 48| </div> 49| <a href="https://twitter.com/intent/tweet?text=I%20uploaded%20an%20image&url=http%3A%2F%2Fpasteboard.co/<%= imageName %>" class="twitter button social" target="__blank" data-track="Twitter Image" title="Share on Twitter"><span class="icon"></span></a> 50| <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fpasteboard.co/<%= imageName %>" class="facebook button social" target="__blank" data-track="Facebook Image" title="Share on Facebook"><span class="icon"></span></a> longURL is not defined

    45|
    46| URL:
    >> 47|
    48| 

49|
50|
longURL is not defined
at eval (eval at (/srv/www/pasteboard/node_modules/ejs/lib/ejs.js:223:12), :29:2335)
at /srv/www/pasteboard/node_modules/ejs/lib/ejs.js:225:15
at Object.exports.render (/srv/www/pasteboard/node_modules/ejs/lib/ejs.js:263:13)
at View.exports.renderFile [as engine] (/srv/www/pasteboard/node_modules/ejs/lib/ejs.js:289:22)
at View.render (/srv/www/pasteboard/node_modules/express/lib/view.js:75:8)
at Function.app.render (/srv/www/pasteboard/node_modules/express/lib/application.js:501:10)
at ServerResponse.res.render (/srv/www/pasteboard/node_modules/express/lib/response.js:755:7)
at exports.index.get.index (/srv/www/pasteboard/controllers/images.coffee:33:16)
at callbacks (/srv/www/pasteboard/node_modules/express/lib/router/index.js:161:37)
at param (/srv/www/pasteboard/node_modules/express/lib/router/index.js:135:11)
```

**Comment by ThaMunsta** [comment]
Short URLs were recently removed. Take a look at "/controllers/main.coffee" and make sure you have something like
`longURL = "http://#{domain}/#{fileName}"`
Might be all that's missing.
